language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
env:
  matrix:
  - PYMATGEN_VERSION=2019.10.16
before_install:
  - pip install --upgrade pip coverage codecov
  - pip install pymatgen==$PYMATGEN_VERSION
install:
  - pip install .
# command to run tests
script:
  - cd tests && coverage run --source=../maptool -m unittest -v && coverage report && cd ..
after_success:
  - codecov

